<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Logout' => 'Wyloguj',
    'Reset' => 'Resetuj',
    'Update {modelClass}: ' => 'Aktualizuj {modelClass}',
    'Add Document' => 'Dodaj dokument',
    'Admin' => 'Administrator',
    'Approve Documents' => 'Zatwierdź dokumenty',
    'Approver' => 'Zatwierdzający',
    'Approver Management' => 'Zarządzanie zatwierdzającymi',
    'Approvers' => 'Zatwierdzający',
    'Are you sure you want to delete this item?' => 'Czy jesteś pewny żeby usunąć ten element?',
    'Authentication' => 'Uwiarygodnienie',
    'Contributor' => 'Kontrybutor',
    'Contributor Management' => 'Zarządzanie kontrybutorami',
    'Contributors' => 'Kontrybutorzy',
    'Create' => 'Stwórz',
    'Create Approver' => 'Stwórz zatwierdzającego',
    'Create Contributor' => 'Stwórz kontrybutora',
    'Create Department' => 'Stwórz departament',
    'Create Document' => 'Stwórz dokument',
    'Create Document Category' => 'Stwórz kategorie dokumentów',
    'Create Reviewer' => 'Stwórz recenzenta',
    'Create User' => 'Stwórz użytkownika',
    'Created At' => 'Utworzono',
    'Created By' => 'Utworzono przez',
    'Data Path' => 'Ścieżka danych',
    'Default' => 'Domyślny',
    'Delete' => 'Usuń',
    'Department' => 'Departament',
    'Department ID' => 'Nr departamentu',
    'Department Management' => 'Zarządzanie departamentami',
    'Departments' => 'Departamenty',
    'Document Categories' => 'Kategorie dokumentów',
    'Document Category' => 'Kategoria dokumentów',
    'Document Category Management' => 'Zarządzanie kategoriami dokumentów',
    'Document ID' => 'Nr dokumentu',
    'Document Management System credentials' => 'Dane dostępu do Systemu Zarządzania Dokumentami',
    'Documents' => 'Dokumenty',
    'Extension' => 'Rozszerzenie',
    'File' => 'Plik',
    'File Format' => 'Format pliku',
    'Home' => 'Strona Domowa',
    'ID' => 'Nr',
    'Is Archived' => 'Zarchiwowany',
    'Is Checked Out' => 'Wylogowany',
    'Language' => 'Język',
    'Login' => 'Zaloguj',
    'Logo' => 'Logo',
    'Name' => 'Nazwa',
    'Path' => 'Ścieżka',
    'Reference Number' => 'Nr referencyjny',
    'Review Documents' => 'Recenzuj dokumenty',
    'Reviewer' => 'Recenzent',
    'Reviewer Management' => 'Zarządzanie recenzentami',
    'Reviewers' => 'Recenzenci',
    'Revision Number' => 'Nr rewizji',
    'Revision Path' => 'Ścieżka rewizji',
    'Search' => 'Szukaj',
    'Select' => 'Wybierz',
    'Status' => 'Status',
    'Steps' => 'Kroki',
    'System' => 'System',
    'System Management' => 'Zarządzanie systemem',
    'Theme' => 'Motyw',
    'Title' => 'Tytuł',
    'Update' => 'Akutalizuj',
    'Updated At' => 'Zaktualizowano',
    'Updated By' => 'Zaktualizowano przez',
    'User ID' => 'Nr użytkownika',
    'User Management' => 'Zarządzanie użytkownikami',
    'Users' => 'Użytkownicy',
    'Workflow' => 'Obieg',
];
